version: 2.1

executors:
  my-executor:
    docker:
      - image: cimg/node:14.17.0
    working_directory: ~/repo

jobs:
  build:
    executor: my-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build Application
          command: npm run build
      - save_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Test Application
          command: npm test 
  hold:
    filters:
      branches:
        only: master    
  deploy:
    executor: my-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Deploy to Firebase
          command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN" --only hosting
    filters:
      branches:
        only: master

workflows:
  build_and_test:
    jobs:
      - build:
          context: movie-queue
      - hold:
          type: approval
          requires:
            - build
      - deploy:
          requires:
            - hold
          context: movie-queue
